### ISSUE TITLE
make `transition` accept a class instead of `fixed_hash_string`

### ISSUE THREAD

**Issue by uyha** [boost-ext/sml2#1]
In the original `sml`, I frequently use `state<some_class>` to annotate the state, this prevents typo and also allows hierarchical state machine (I'm not sure if `sml2` supports hierarchical state machine yet). So I think it's a better to use types (or concepts).

**Comment by krzysztof-jusiak** [comment]
Agree, I believe this part of the original design was correct and we should extend sml2 with that too.

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/boost-ext/sml2/commit/f55a9b45af8f7d6362587692e4244a33dce58c7a
