### ISSUE TITLE
How to add entry/exit actions for state?

### ISSUE THREAD

**Issue by liziyi75** [boost-ext/sml2#3]
I wish to  add entry/exit actions for state.

**Comment by krzysztof-jusiak** [comment]
Yeah, that's exactly the plan, will be added as soon as possible.

**Comment by Klaim** [comment]
Any estimation of when this would be available, even if not in a release yet?
I would like to try this library in a project I started recently but entry and exit state functions are mandatory for my case.

**Comment by liziyi75** [comment]
> Any estimation of when this would be available, even if not in a release yet? I would like to try this library in a project I started recently but entry and exit state functions are mandatory for my case.

+1

**Comment by krzysztof-jusiak** [comment]
Sorry for the delay. Either way, it's on my list to add before the end of the year, so hopefully, it will be this or next weekend.

**Comment by krzysztof-jusiak** [comment]
Sorry for the delay, on_entry/on_exit have been now implemented

Example usage

```
    struct e1 {};
    struct e2 {};

    int on_entry_calls{};
    int on_exit_calls{};

    sm sm = [&] {
        using namespace dsl;
        return transition_table{
            *"s1"_s + event<e1> = "s2"_s,
            "s2"_s + on_entry / [&] { ++on_entry_calls; },
            "s2"_s + on_exit / [&] { ++on_exit_calls; },
            "s2"_s + event<e2> = "s3"_s,
        };
    };

    using dsl::operator""_s;
    assert(sm.process_event(e1{}));
    assert(sm.is("s2"_s));
    assert(on_entry_calls == 1);
    assert(on_exit_calls == 0);
    assert(sm.process_event(e2{}));
    assert(on_entry_calls == 1);
    assert(on_exit_calls == 1);
    assert(sm.is("s3"_s));
```

- https://godbolt.org/z/d88331aqo
